#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# npm run lint:prettier:fix
# npm run lint:stylelint:fix
# npm run lint:eslint:fix
# npm run test:unit
# npm run storybook:build
# npm run test:ui:ci
